### ISSUE TITLE
Create a utility database containing default values.

### ISSUE THREAD

**Issue by amSiddiqui** [TheKeySpammer/AccountingSoftware#10]
Create a database the contains the following values for user completion.

- [x] Countries

- [x] Currencies

- [x] Phone area code

- [x] Supported Date Formats

- [x] Famous Business Quotes (to display on dashboard)

**Comment by abhishekk1098** [comment]
Created Countries,Currency and Phoencode database.

**Comment by asrninaad** [comment]
Created and Populated Date_Format and Quotes.
