### ISSUE TITLE
Create company create route in database

### ISSUE THREAD

**Issue by amSiddiqui** [TheKeySpammer/AccountingSoftware#21]
Create **/auth/signup** route on database server. 
## Specifications
**Method:** Post
### Request 
accessToken: String
company: Object (type company)
    **Company object specification**
```
{
company: {     
name:
countryCode:
phone:
email:
address: {}
currency: 
datefmt:
taxrate:
accountants: ['Head', 'Client', 'Expense', 'General']
profilesCreated: // length of accountants array 
}
headAcc: {
// Details of Head accountant including password
}
clientAcc: {
}
expenseAcc: {
}
generalAcc: {

}
}
```

headAcc: {
accountantType: 'Head'
firstName: 
lastName:
countryCode:
phone:
email:
address: {
address1:
city:
state:
country:
pincode:
},
password:
}

**Note**: headAcc, clientAcc etc will only be present if included in accountants array inside company

### Response
status: number (click [here](https://www.restapitutorial.com/httpstatuscodes.html) for reference)
token: String (encrypted) (for Head Accountant)
err: String

### Token generation
headAccountant.email + currentTime

### Conditions
if accessToken doesn't matches: Authorisation error
if userToken already exist: user already logged in error
if any data already present in database: Already present error

**Comment by asrninaad** [comment]
Please check for any problems and tell me.
